CREATE TABLE IF NOT EXISTS sessions (
    id           CHAR(72) PRIMARY KEY,
    session_data TEXT
);
CREATE TABLE IF NOT EXISTS entry (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    body TEXT,
    ctime INT UNSIGNED NOT NULL,
    utime INT UNSIGNED,
    author_name VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS user_tbl (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    login_name VARCHAR(30),
    login_password VARCHAR(30),
    user_name VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;